### ISSUE TITLE
On Windows 10 Chrome 90 these snippets are not colored

### ISSUE THREAD

**Issue by frederikhors** [go-bun/bun-docs#1]
On Windows 10 Chrome 90 these snippets are not colored: https://bun.uptrace.dev/guide/fixtures.html#creating-fixtures.

![image](https://user-images.githubusercontent.com/41120635/120213866-056c3e80-c234-11eb-8ae1-9c12b525f4ff.png)

**Comment by vmihailenco** [comment]
Should be fixed. Thanks for the report.
